name: devotee_matrimony
description: "A new Flutter project."
version: 1.0.0+1
environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  animated_custom_dropdown: 3.1.1
  flutter_svg: ^2.0.10+1
  floating_bottom_bar: ^0.0.3
  stylish_bottom_bar: ^1.1.0
  easy_radio: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Medium.ttf
        - asset: fonts/poppins/Poppins-SemiBold.ttf
        - asset: fonts/poppins/Poppins-Bold.ttf